#### general settings
name: motion-blur-SR
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [1]
pca_matrix_path: /tn/work3/FSRDiff-blur/pca_matrix/DCLS/pca_matrix.pth

# degradation:
#   random_kernel: True
#   ksize: 21
#   code_length: 10
#   sig_min: 0.2
#   sig_max: 4.0
#   rate_iso: 1.0
#   random_disturb: false

#### datasets
datasets:
  train:
    is_train: True
    name: GoPro
    mode: GT
    dataroot_GT: /tn/diffGAN-srd/data/dataset/GoPro/HR.lmdb

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 16 #64
    GT_size: 256 #256
    LR_size: 64 #64
    use_flip: true
    use_rot: true
    color: RGB
    
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: /tn/Data/test/GoPro/
    dataroot_LQ: /tn/Data/test/GoPro/

#### network structures
network_G:
  which_model_G: RM
  setting:
    nf: 64
    nb: 10
    ng: 5
    input_para: 256
    kernel_size: 21

# #### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
